pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh "mkdir output"
                dotnet build /src -o output
            }
        }
        stage('Test') {
            steps {
                dotnet test /tests
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}