pipeline {
    agent any
    stages {
        stage('Prep') {
            steps {
                    echo '========================================'
                    sh "dotnet --version";
            }
        }
        stage('Build') {
            steps {
                sh "dotnet build /src -o output"
            }
        }
        stage('Test') {
            steps {
                sh "dotnet test /tests"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}